name: Create new github release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  maven-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - run: git config --global user.email "tvpozytyw@gmail.com"
      - run: git config --global user.name "github-action"

      - name: Maven release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ACTOR_NAME: ${{ github.actor }}
        run: |
          mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B release:prepare --file pom.xml
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - run: echo $TAG

      - name: Release pushed tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$TAG" \
              --generate-notes

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: Dockerfile.base
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
